### ISSUE TITLE
angry birds游戏相关

### ISSUE THREAD

**Issue by jaylbj37** [NobyDa/ND-AD#11]
规则导致angry birds相关游戏登录不了，同步不了数据，希望可以移除。多谢。

**Comment by NobyDa** [comment]
已移除, 可以试下是否正常.

**Comment by jaylbj37** [comment]
不知道还是否与我fb登录有关，一直在处理中，登陆不了

**Comment by NobyDa** [comment]
在网络请求里找一下是哪条规则导致的, 尝试单独添加proxy规则.

**Comment by jaylbj37** [comment]
解决了，问题不在于angrybirdsgame。删除cloud.rovio.com可解决，非常感谢。
