### ISSUE TITLE
错误 Invalid line <!doctype html>

### ISSUE THREAD

**Issue by charlesgth** [NobyDa/ND-AD#18]
![4DC946B0-FDED-46FB-9AFD-11476165641D](https://user-images.githubusercontent.com/72912780/96095590-65aaac00-0f01-11eb-8e7d-d220327915fb.jpeg)

Quantumult x 添加时提示
请问该如何解决？

**Comment by NobyDa** [comment]
去相关规则文件顶部拿raw直链

**Comment by charlesgth** [comment]
> 去相关规则文件顶部拿raw直链

谢谢作者
